### ISSUE TITLE
[Server] 모달과 연동해서 로그인, 회원가입 구현

### ISSUE THREAD

**Issue by greenheadHQ** [codestates/BanThing#125]
### TODO
* 로그인 / 회원가입 모달
  - [x] 클라이언트와 연결해서 로그인 구현
  - [x] 클라이언트와 연결해서 회원가입 구현
* 회원정보 수정
  - [x] 비밀번호 수정
  - [x] 회원탈퇴
* 유효성 검사 
  - [x] 중복 확인
  - [x] 알맞은 타입 검사
 
### Estimated time
> 3d+
