### ISSUE TITLE
[Client] Modal 스타일링 및 기능 구현

### ISSUE THREAD

**Issue by slight-snow** [codestates/BanThing#39]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: Styling Modal and create feature

### TODO
  - [ ] 로그인 메뉴를 클릭했을 때 Modal 창 띄우기
     - [ ] Login Modal - Login 버튼 및 기능 구현
     - [ ] Login Modal 내에서 유효성 검사 구현
     - [ ] Login Modal - 회원가입 버튼 및 기능 구현
  - [ ] 회원가입 버튼을 눌렀을 때 Modal 창 띄우기
     - [ ] 아이디 중복 확인 기능 구현
     - [ ] 닉네임 중복 확인 기능 구현
     - [ ] 아이디 유효성 검사 구현
     - [ ] 닉네임 유효성 검사 구현
     - [ ] 비밀번호와 비밀번호 확인 일치 검사 구현
     - [ ] 입력된 내용을 바탕으로 회원가입 기능 구현
 
### Labels
- Estimated time: `E: 2d+`
- Group : `client`
- Sprint: `Sprint2`
- Urgency: `Middle`
