### ISSUE TITLE
[Client] Login 스타일링 및 기능 구현

### ISSUE THREAD

**Issue by slight-snow** [codestates/BanThing#43]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: Styling Login and create feature

### TODO
  - [ ] 아이디와 비밀번호가 일치할 경우
    - [ ] Main Page 로 리다이렉트
    - [ ] 토큰 저장
  - [ ] 아이디와 비밀번호가 일치하지 않을 경우
    - [ ] 둘을 묶어 '아이디 혹은 비밀번호가 일치하지 않습니다.' 경고문구가 나오도록 구현
  - [ ] Prototype 에 기반하여 퍼스널 컬러 입히기 및 디자인하기 
 
### Labels
- Estimated time: `E: 1d+`
- Group : `client`
- Sprint: `Sprint3`
- Urgency: `Middle`
