### ISSUE TITLE
[Client] Header 스타일링

### ISSUE THREAD

**Issue by greenheadHQ** [codestates/BanThing#62]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: Styling Header and create feature

### TODO
   - [x] 로고, 네비게이션 바 디자인 구현
   - [x] 로고를 눌렀을 때 Main Page 로 이동하도록 구현
   - [x] 나머지 메뉴들 각각 HOME, MAIN 은 눌렀을 때 Landing Page, Main Page 로 이동하도록 구현
   - [x] LOGIN 메뉴 클릭시 이동없이 Login 모달창만 나오게 구현
   - [x] LOGIN 여부에 따라 LOGOUT 과 프로필이 표시되도록 구현
     (프로필은 임시 이미지를 사용합니다.)
   - [x] 프로필을 클릭할 경우 My Page 로 이동하도록 구현
 
### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1d+`
- Group : `client`
- Sprint: `Sprint2`
- Urgency: `Low`
