### ISSUE TITLE
[Client] Landing 스타일링

### ISSUE THREAD

**Issue by greenheadHQ** [codestates/BanThing#64]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: Styling Landing Page & Create features of Landing Page

### TODO
 - [x] 최상단에 표시되는 Main Component 구현하기
   - [x] Main Page 로 이동하는 '시작하기' 버튼 구현
   - [ ] 실제 사용 Gif 이미지 첨부하기
          (Main Page 가 모두 구현되기 전까지는 임시 Gif 파일을 사용합니다.)
 - [x] Side Component 1, 2, 3, 4, 5, 6 구현하기
   - [x] Side Component 1) <혼자 먹기에는 부담스러운 배달음식>
   - [x] Side Component 2) <BanThing 이 해결해드리겠습니다!>
   - [x] Side Component 3) <내 주변의 배달 메이트 확인>
   - [x] Side Component 4) <배달 메이트와의 실시간 메뉴 선정>
   - [x] Side Component 5) <배달 메이트 레이팅 시스템>
   - [x] Side Component 6) <당신만 준비되었다면, 바로 시작해봅시다!>
 - [x] 페이지 스크롤을 내릴수록 진행도가 표시되는 진행바 구현하기
 - [ ] 모바일 반응형 페이지 구현하기
 
### Labels
- Estimated time: `E: 3d+`
- Group : `client`
- Sprint: `Sprint1`
- Urgency: `Middle`
