### ISSUE TITLE
[Client] MyPage 스타일링

### ISSUE THREAD

**Issue by greenheadHQ** [codestates/BanThing#68]
### ISSUE
- Group: `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
 - [x] 사용자의 프로필 이미지를 상단에 표시
 - [x] 사용자의 평점을 프로필 이미지 하단에 표시
 - [x] 아이디, 닉네임 칸은 수정 불가능하도록 구현
 - [x] 비밀번호 변경, 비밀번호 확인 칸 구현
 - [x] 수정하기 버튼 구현
 - [x] 회원탈퇴 버튼 구현
 
### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
